server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 47.93.221.98
    port: 63759
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.4.230:33306/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: master518
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou  #密钥
  cookieDomain: ${spring.cloud.client.ip-address}
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks  #证书位置
    secret: changgou  #密钥
    alias: changgou
    password: changgou
#开启容断器
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时设置，默认为1秒
            timeoutInMilliseconds: 10000
          #  隔离模式使用信号量隔离SEMAPHORE 默认值是线程隔离THREAD
          strategy: SEMAPHORE
thymeleaf:
  cache: false


